<a href="https://colab.research.google.com/github/vishnuvryeruva/Generating-Text-Sequence/blob/main/Generating_Text_Sequence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# keras module for building LSTM 
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.preprocessing.text import Tokenizer
from keras.callbacks import EarlyStopping
from keras.models import Sequential
import keras.utils as ku 

# set seeds for reproducability
import tensorflow
from numpy.random import seed
tensorflow.random.set_seed(2)
seed(1)

import pandas as pd
import numpy as np
import string, os 

import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore', category=FutureWarning)

Data Loading

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Data/ArticlesMarch2018.csv')
data.head()

articleID                                        byline  \
0  5a974697410cf7000162e8a4                         By BINYAMIN APPELBAUM   
1  5a974be7410cf7000162e8af             By HELENE COOPER and ERIC SCHMITT   
2  5a9752a2410cf7000162e8ba                        By THE EDITORIAL BOARD   
3  5a975310410cf7000162e8bd                        By JAVIER C. HERNÁNDEZ   
4  5a975406410cf7000162e8c3  By JESSE DRUCKER, KATE KELLY and BEN PROTESS   

  documentType                                           headline  \
0      article                      Virtual Coins, Real Resources   
1      article       U.S. Advances Military Plans for North Korea   
2      article                 Mr. Trump and the ‘Very Bad Judge’   
3      article     To Erase Dissent, China Bans Pooh Bear and ‘N’   
4      article  Loans Flowed to Kushner Cos. After Visits to t...   

                                            keywords  multimedia     newDesk  \
0  ['Bitcoin (Currency)', 'Electric Light and Pow...           1    Business   
1  ['United States Defense and Military Forces', ...           1  Washington   
2  ['Trump, Donald J', 'Curiel, Gonzalo P', 'Unit...           1   Editorial   
3  ['China', 'Xi Jinping', 'Term Limits (Politica...           1     Foreign   
4  ['Kushner, Jared', 'Kushner Cos', 'United Stat...           1    Business   

   printPage              pubDate   sectionName  \
0          1  2018-03-01 00:17:22       Economy   
1         11  2018-03-01 00:40:01  Asia Pacific   
2         26  2018-03-01 01:08:46       Unknown   
3          1  2018-03-01 01:10:35  Asia Pacific   
4          1  2018-03-01 01:14:41       Unknown   

                                             snippet              source  \
0  America has a productivity problem. One explan...  The New York Times   
1  The American military is looking at everything...  The New York Times   
2  Can you guess which man is the model public se...  The New York Times   
3  Censors swung into action after Mr. Xi’s bid t...  The New York Times   
4  Apollo, the private equity firm, and Citigroup...  The New York Times   

  typeOfMaterial                                             webURL  \
0           News  https://www.nytimes.com/2018/02/28/business/ec...   
1           News  https://www.nytimes.com/2018/02/28/world/asia/...   
2      Editorial  https://www.nytimes.com/2018/02/28/opinion/tru...   
3           News  https://www.nytimes.com/2018/02/28/world/asia/...   
4           News  https://www.nytimes.com/2018/02/28/business/ja...   

   articleWordCount  
0              1207  
1              1215  
2              1043  
3              1315  
4              1566

In [4]:
headlines = []
headlines.extend(list(data.headline.values))
headlines = [h for h in headlines if h != "Unknown"]
len(headlines)

1250

Cleaning

In [5]:
#removal of punctuations and lower casing all the words
def clean_text(txt):
    txt = "".join(v for v in txt if v not in string.punctuation).lower()
    txt = txt.encode("utf8").decode("ascii",'ignore')
    return txt 

corpus = [clean_text(x) for x in headlines]
corpus[:10]

['virtual coins real resources',
 'us advances military plans for north korea',
 'mr trump and the very bad judge',
 'to erase dissent china bans pooh bear and n',
 'loans flowed to kushner cos after visits to the white house',
 'china envoy intends to ease trade tensions',
 'president trumps contradictory and sometimes false comments about gun policy to lawmakers',
 'classic letter puzzle',
 'silicon valley disruption in an australian school',
 'the assassination of gianni versace episode 6 a nothing man']

Tokenization

Tokenization is a process of extracting tokens (terms / words) from a corpus.

In [6]:
tokenizer = Tokenizer()

def get_sequence_of_tokens(corpus):
    ## tokenization
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index) + 1
    
    ## convert data to sequence of tokens 
    input_sequences = []
    for line in corpus:
        token_list = tokenizer.texts_to_sequences([line])[0]
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
            input_sequences.append(n_gram_sequence)
    return input_sequences, total_words

inp_sequences, total_words = get_sequence_of_tokens(corpus)
inp_sequences[:10]

[[1119, 1120],
 [1119, 1120, 116],
 [1119, 1120, 116, 1121],
 [31, 1122],
 [31, 1122, 589],
 [31, 1122, 589, 392],
 [31, 1122, 589, 392, 7],
 [31, 1122, 589, 392, 7, 61],
 [31, 1122, 589, 392, 7, 61, 70],
 [117, 10]]

Padding the sequences

we need to pad the sequences and make their lengths equal. We can use pad_sequence function of Kears for this purpose

In [7]:
def generate_padded_sequences(input_sequences):
    max_sequence_len = max([len(x) for x in input_sequences])
    input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
    
    predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
    label = ku.np_utils.to_categorical(label, num_classes=total_words)
    return predictors, label, max_sequence_len

predictors, label, max_sequence_len = generate_padded_sequences(inp_sequences)
print(predictors)
print(label)

[[   0    0    0 ...    0    0 1119]
 [   0    0    0 ...    0 1119 1120]
 [   0    0    0 ... 1119 1120  116]
 ...
 [   0    0    0 ...  979  151  386]
 [   0    0    0 ...    0    0 3581]
 [   0    0    0 ...    0 3581    5]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Applying LSTM for Text generation

**Input Layer:** Takes the sequence of words as input

**LSTM Layer:** Computes the output using LSTM units. I have added 100 units in the layer, but this number can be fine tuned later.

**Dropout Layer:** A regularisation layer which randomly turns-off the activations of some neurons in the LSTM layer. It helps in preventing over fitting. (Optional Layer)

**Output Layer:** Computes the probability of the best possible next word as output


In [8]:
def create_model(max_sequence_len, total_words):
    input_len = max_sequence_len - 1
    model = Sequential()
    
    # Add Input Embedding Layer
    model.add(Embedding(total_words, 10, input_length=input_len))
    
    # Add Hidden Layer 1 - LSTM Layer
    model.add(LSTM(100))
    model.add(Dropout(0.1))
    
    # Add Output Layer
    model.add(Dense(total_words, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam')
    
    return model

model = create_model(max_sequence_len, total_words)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 17, 10)            35820     
                                                                 
 lstm (LSTM)                 (None, 100)               44400     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense (Dense)               (None, 3582)              361782    
                                                                 
Total params: 442,002
Trainable params: 442,002
Non-trainable params: 0
_________________________________________________________________


Training

In [9]:
model.fit(predictors, label, epochs=100, verbose=5)

Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 74/100
Epoch 75/100
Epoch 76/100
Epoch 77/100
Epoch 78

Generating the Text

predicting the next word based on the input words (or seed text).

In [10]:
def generate_text(seed_text, next_words, model, max_sequence_len):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
        predicted = model.predict(token_list, verbose=0)
        output_word = ""
        for word,index in tokenizer.word_index.items():
            if index == predicted:
                output_word = word
                break
        seed_text += " "+output_word
    return np.allclose(seed_text.title())
    print(max_sequence_len,model,seed_text )